In [3]:
import halo_analysis as halo
import numpy as np
import pandas as pd

In [33]:
gals = [
    'm12f_res7100',
    'm12i_res7100',
    'm12w_res7100',
    'm12m_res7100'
]

def scaleRadii(sim_dir, snapshot):
    halt = halo.io.IO.read_tree(simulation_directory=sim_dir, species='star', species_snapshot_indices=[snapshot])
    current_idx = np.where((halt['snapshot'] == 600))
    r_vir     = halt['radius'][halt['host.index'][current_idx]][0]
    r_star_90 = halt['star.radius.90'][halt['host.index'][current_idx]][0]
    
    df = {
        'virial': [r_vir],
        'star.radius.90': [r_star_90]
    }
    
    return pd.DataFrame(df)

In [34]:
for sim in gals:
    sim_dir = '../data/latte_metaldiff/' + sim
    df = scaleRadii(sim_dir, 600)
    df.to_hdf('radii_{}.hdf'.format(sim), 'w')


# in utilities.simulation.Snapshot():
* reading:  data/latte_metaldiff/m12f_res7100/snapshot_times.txt

* read 28366111 halos from:  data/latte_metaldiff/m12f_res7100/halo/rockstar_dm/catalog_hdf5/tree.hdf5
  
* assigning ['star'] properties to halo merger trees
* read 59184 halos, 63 have star particles, from:  data/latte_metaldiff/m12f_res7100/halo/rockstar_dm/catalog_hdf5/star_600.hdf5

# in utilities.simulation.Snapshot():
* reading:  data/latte_metaldiff/m12f_res7100/snapshot_times.txt

  dark2.mass
  star.form.time.100
  star.form.time.50
  star.form.time.90
  star.form.time.95
  star.form.time.dif.68
  star.indices
  star.mass
  star.massfraction
  star.number
  star.position
  star.radius.50
  star.radius.90
  star.vel.circ.50
  star.vel.std
  star.vel.std.50
  star.velocity


# in utilities.simulation.Snapshot():
* reading:  data/latte_metaldiff/m12i_res7100/snapshot_times.txt

* read 17859917 halos from:  data/latte_metaldiff/m12i_res7100/halo/rockstar_dm/catalog_hdf5/tree.h

In [2]:
halt = halo.io.IO.read_tree(simulation_directory='../data/latte_metaldiff/m12f_res7100', species='star', species_snapshot_indices=[600], assign_species_pointers=True)


# in utilities.simulation.Snapshot():
* reading:  data/latte_metaldiff/m12f_res7100/snapshot_times.txt


# in halo_analysis.halo_io.IO():
* read 28366111 halos from:  data/latte_metaldiff/m12f_res7100/halo/rockstar_dm/catalog_hdf5/tree.hdf5
  
* assigning ['star'] properties to halo merger trees

# in halo_analysis.halo_io.Particle():
* read 59184 halos, 63 have star particles, from:  data/latte_metaldiff/m12f_res7100/halo/rockstar_dm/catalog_hdf5/star_600.hdf5

# in utilities.simulation.Snapshot():
* reading:  data/latte_metaldiff/m12f_res7100/snapshot_times.txt

! cannot find star particle pointer file at snapshot 600 in ../data/latte_metaldiff/m12f_res7100/
  dark2.mass
  star.form.time.100
  star.form.time.50
  star.form.time.90
  star.form.time.95
  star.form.time.dif.68
  star.indices
  star.mass
  star.massfraction
  star.number
  star.position
  star.radius.50
  star.radius.90
  star.vel.circ.50
  star.vel.std
  star.vel.std.50
  star.velocity



In [4]:
pd.read_hdf('radii_m12m_res7100.hdf')

virial  star.radius.90
0  341.613953       12.620866

In [37]:
halt['star.radius.90']

array([-1., -1., -1., ..., -1., -1., -1.], dtype=float32)

In [16]:
print()

dict_keys(['am.phantom', 'am.progenitor.main', 'axis.b/a', 'axis.c/a', 'catalog.index', 'central.index', 'central.local.index', 'descendant.index', 'descendant.snapshot', 'dindex', 'final.index', 'host.distance', 'host.index', 'host.velocity', 'host.velocity.rad', 'host.velocity.tan', 'major.merger.snapshot', 'mass', 'mass.180m', 'mass.200c', 'mass.200m', 'mass.500c', 'mass.bound', 'mass.lowres', 'mass.vir', 'position', 'position.offset', 'progenitor.co.dindex', 'progenitor.co.index', 'progenitor.last.dindex', 'progenitor.main.index', 'progenitor.main.last.dindex', 'progenitor.number', 'radius', 'scale.radius', 'scale.radius.klypin', 'snapshot', 'spin.bullock', 'spin.peebles', 'tid', 'vel.circ.max', 'vel.std', 'velocity', 'velocity.offset', 'dark2.mass', 'star.form.time.100', 'star.form.time.50', 'star.form.time.90', 'star.form.time.95', 'star.form.time.dif.68', 'star.indices', 'star.mass', 'star.massfraction', 'star.number', 'star.position', 'star.radius.50', 'star.radius.90', 'star.v

In [47]:
np.where(halt['star.radius.90'] != -1)[0]

array([  981831,  3577119,  4061758,  4527938,  4702402,  4821545,
        4889516,  4979056,  5090844,  5143219,  5193817,  5228384,
        5319841,  5354881,  5485030,  5498371,  5566400,  5580672,
        5591198,  5610045,  5643171,  5683520,  5710028,  5724591,
        5781622,  5802785,  5809222,  5848383,  5867351,  5891526,
        5981970,  5991827,  6005677,  6026627,  6039560,  6050201,
        6076409,  6098373,  6122923,  6128820,  6147823,  6214528,
        6225999,  6232757,  6237993,  6252835,  6270053,  6280962,
        6295775,  6312513,  6348746,  6351870,  6369436,  6382315,
        6387171,  6441160,  6472283,  6509797,  6569600,  6577453,
        6596546,  6612391,  6615819,  6631605,  6642473,  6655721,
        6683415,  6685691,  6767204,  6826903,  6836375,  6841032,
        6853398,  6856983,  6923721,  6963320,  6972297,  7029830,
        7073932,  7129766,  7137943,  7144886,  7189047,  7266567,
        7287434,  7294162,  7380864,  7425604,  7450829,  7485

In [49]:

np.argmax(halt['mass.bound'][np.where(halt['star.radius.90'] != -1)[0]])

0

In [5]:
np.where((halt['snapshot'] == 600) & (halt['star.radius.90'] != -1))[0][0]

0

In [9]:
halt[np.where(halt['snapshot']==600)[0]]

TypeError: unhashable type: 'numpy.ndarray'

In [32]:
halt['radius'][halt['host.index'][np.where(halt['snapshot']==600)]]

array([354.66098, 354.66098, 354.66098, ..., 354.66098, 354.66098,
       354.66098], dtype=float32)